masterdata:
  tenants:
    od.belpahar
    od.anandapur
    od.khandapada
    od.padampur
    od.jagatsinghpur
    od.sambalpurdevelopmentauthority
    od.konark
    od.gudari
    od.bhanjanagar
    od.nimapara
    od.paradipdevelopmentauthority
    od.dhamnagar
    od.paradeep
    od.kabisuryanagar
    od.kesinga
    od.soro
    od.kashinagar
    od.balimela
    od.khariar
    od.pattamundai
    od.junagarh
    od.ganjam
    od.bargarh
    od.bijepur
    od.barpali
    od.dhenkanal
    od.talcher
    od.birmitrapur
    od.kuchinda
    od.khordha
    od.polasara
    od.berhampur
    od.chatrapur
    od.purushottampur
    od.pipli
    od.brajrajnagar
    od.kodala
    od.balasore
    od.purikonarkdevelopmentauthority
    od.nabarangpur
    od.angul
    od.bhuban
    od.bhubaneswar
    od.aska
    od.jajpur
    od.digapahandi
    od.puri
    od.bellaguntha
    od.nuapada
    od.jaleswar
    od.rayagada
    od.balangir
    od.baripada
    od.vyasanagar
    od.kotpad
    od.phulbani
    od.bhawanipatna
    od.gunupur
    od.sunabeda
    od.boudhgarh
    od.cuttackdevelopmentauthority
    od.balugaon
    od.athagarh
    od.dharamgarh
    od.champua
    od.barbil
    od.jharsuguda
    od.kantabanji
    od.banpur
    od.banki
    od.gudayagiri
    od.rourkela
    od.khallikote
    od.jatni
    od.attabira
    od.berhampurdevelopmentauthority
    od.odagaon
    od.sambalpur
    od.balliguda
    od.titilagarh
    od.talcherangulmeramandalidevelopmentauthority
    od.kamakhyanagar
    od.gopalpur
    od.buguda
    od.bhadrak
    od.jeypore
    od.nilgiri
    od.joda
    od.khariarroad
    od.nayagarh
    od.chikiti
    od.deogarh
    od.koraput
    od.choudwar
    od.hindol
    od.athmallik
    od.tarbha
    od.basudevpur
    od.rairangpur
    od.binka
    od.umerkote
    od.bhubaneswardevelopmentauthority    
    od.chandbali
    od.ranpur
    od.malkangiri
    od.karanjia
    od.keonjhargarh
    od.kendrapara
    od.udala
    od.surada
    od.hinjilicut
    od.patnagarh
    od.kalinganagardevelopmentauthority
    od.daspalla
    od.paralakhemundi
    od.redhakhol
    od.sundargarh
    od.rourkeladevelopmentauthority
    od.cuttack
    od.tusura
    od.sonepur
    od.rambha
    od.rajgangpur
 
        